// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1764352822);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 161);
user_pref("browser.newtabpage.activity-stream.impressionId", "{df46fed8-0fc1-461a-bce1-ce599c24cd7f}");
user_pref("browser.newtabpage.activity-stream.system.showWeatherOptIn", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1764352823);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1764352824465");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1764374424465");
user_pref("browser.search.region", "SE");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20251125050421");
user_pref("browser.startup.homepage_override.mstone", "145.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1764352824);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"zen-sidebar-top-buttons\":[\"zen-toggle-compact-mode\"],\"zen-sidebar-foot-buttons\":[\"downloads-button\",\"zen-workspaces-button\",\"zen-create-new-button\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"zen-sidebar-foot-buttons\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 3);
user_pref("captchadetection.lastSubmission", 1764352);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "48394bd9-1d00-485b-80a7-2117f89b5c6c");
user_pref("datareporting.dau.cachedUsageProfileID", "7a58d6d3-4a69-4188-87b0-83fe18bc8866");
user_pref("distribution.iniFile.exists.appversion", "1.17.10b");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "SE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "4044f3f87dbf48bc88616fa926bac33a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20251125050421");
user_pref("extensions.lastAppVersion", "1.17.10b");
user_pref("extensions.lastPlatformVersion", "145.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"fdb10a0c-2c36-4c01-b214-ba4b8d836742\",\"formautofill@mozilla.org\":\"ab7afe9c-ed93-453d-9679-86a4c21e55da\",\"ipp-activator@mozilla.com\":\"4c534884-d424-468d-89f9-374d613e6e17\",\"pictureinpicture@mozilla.org\":\"e6901a63-7864-4f8d-9fd4-aec991202efe\",\"addons-search-detection@mozilla.com\":\"d856e8ed-ec45-414e-b3df-4176dc1cf95b\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"08cd4cfd-8682-44a6-8282-af16fa28cb57\",\"default-theme@mozilla.org\":\"24d4759f-ea85-4bec-b826-e587b4991611\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 2);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "592e906b-7d05-4038-979b-fea891e98e6c");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.storeID", "7fa43b52");
user_pref("toolkit.startup.last_success", 1764352821);
user_pref("toolkit.telemetry.cachedClientID", "44d1f679-18b5-4ad6-9cef-69f444b6fdc5");
user_pref("toolkit.telemetry.cachedProfileGroupID", "587880f5-04d7-4b0a-8986-075f3d442d1a");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("zen.keyboard.shortcuts.version", 13);
user_pref("zen.mods.last-update", 1764352823);
user_pref("zen.mods.milestone", "1.17.10b");
user_pref("zen.mods.updated-value-observer", true);
user_pref("zen.ui.migration.compact-mode-button-added", true);
user_pref("zen.ui.migration.version", 5);
user_pref("zen.updates.last-build-id", "20251125050421");
user_pref("zen.updates.last-version", "1.17.10b");
user_pref("zen.welcome-screen.seen", true);
user_pref("zen.workspaces.active", "{e3ac77e3-e622-4534-9993-c84ffe0e813e}");
