general {
    ignore_dbus_inhibit = true    # Turn off backlight even during video playback
    ignore_systemd_inhibit = true
}

listener {
    timeout = 5                                               # 5s
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
    ignore_inhibit = true
}
