general {
    ignore_dbus_inhibit = true    # Turn off backlight even during video playback
    ignore_systemd_inhibit = true
}

listener {
    timeout = 5
    on-timeout = keyboard-backlight-memory idle-off
    on-resume = keyboard-backlight-memory restore
    ignore_inhibit = true
}
