general {
    ignore_dbus_inhibit = true    # Turn off backlight even during video playback
    ignore_systemd_inhibit = true
}

listener {
    timeout = 5                                               # 5s
    on-timeout = brightnessctl -d '*::kbd_backlight' set 0   # turn off keyboard backlight
    on-resume = brightnessctl -d '*::kbd_backlight' set 1    # always restore to default level 1
    ignore_inhibit = true
}
